In [1]:
##### updated pandas

In [2]:
import numpy as np 
import pandas as pd

In [12]:
### data frame is just tables and with extra funcitonlaity 


#we can create a data frame by ourself with like this 
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns =["A","B","C"] , index =["x" ,"y", "z"])
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [13]:
print(df)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [15]:
x = df.index
print(x)

Index(['x', 'y', 'z'], dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [18]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [21]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [22]:
df['A'].unique

<bound method Series.unique of x    1
y    4
z    7
Name: A, dtype: int64>

In [24]:
df.shape

(3, 3)

In [25]:
df.size

9

In [26]:
##################### Load data from files ############

In [33]:
# load a csv 
coffee = pd.read_csv("coffee.csv")

In [34]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [35]:
biox = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")

biox.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [36]:
# csv are readable , undestandable , but size is huge

In [37]:
results = pd.read_parquet("results.parquet")
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [40]:
olympics_data = pd.read_excel("olympics-data.xlsx" , sheet_name="results")

KeyboardInterrupt:

In [ ]:
olympics_data

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [41]:
biox.to_csv("Harivansh.csv")

In [42]:
# accessing data with python
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [43]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [44]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [45]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [46]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [59]:
coffee.sample(6 , random_state=4)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
3     Tuesday       Latte          20
11   Saturday       Latte          35
9      Friday       Latte          35
6    Thursday    Espresso          40
13     Sunday       Latte          35

In [63]:
# loo and iloc
coffee.loc[0:4]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [64]:
coffee.loc[[0,2,4]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
2    Tuesday    Espresso          30
4  Wednesday    Espresso          35

In [68]:
coffee.loc[1:,["Day","Units Sold"]]

          Day  Units Sold
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [71]:
######### iloc use only index

coffee.iloc[1:,[0,1]]

          Day Coffee Type
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [90]:
coffee.index = coffee["Day"]

In [91]:
coffee.iloc["Monday":"Wednesday"]

TypeError: cannot do positional indexing on Index with these indexers [Monday] of type str

In [92]:
coffee.iloc["Monday","Units Sold"]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [93]:
coffee.iloc[0:3,"Units Sold"] = 100

TypeError: Cannot index by location index with a non-integer key

In [94]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso        25.0
Monday        Monday       Latte        15.0
Tuesday      Tuesday    Espresso        30.0
Tuesday      Tuesday       Latte        20.0
Wednesday  Wednesday    Espresso        35.0

In [98]:
coffee.iloc[1,2]

np.float64(15.0)

In [99]:
coffee.Day

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
NaN                NaN
Name: Day, dtype: object

In [100]:
coffee["Units Sold"]

Day
Monday        25.0
Monday        15.0
Tuesday       30.0
Tuesday       20.0
Wednesday     35.0
Wednesday     25.0
Thursday      40.0
Thursday      30.0
Friday        45.0
Friday        35.0
Saturday      45.0
Saturday      35.0
Sunday        45.0
Sunday        35.0
NaN          100.0
Name: Units Sold, dtype: float64

In [103]:
coffee.sort_values(["Units Sold","Coffee Type"])

                 Day Coffee Type  Units Sold
Day
Monday        Monday       Latte        15.0
Tuesday      Tuesday       Latte        20.0
Monday        Monday    Espresso        25.0
Wednesday  Wednesday       Latte        25.0
Tuesday      Tuesday    Espresso        30.0
Thursday    Thursday       Latte        30.0
Wednesday  Wednesday    Espresso        35.0
Friday        Friday       Latte        35.0
Saturday    Saturday       Latte        35.0
Sunday        Sunday       Latte        35.0
Thursday    Thursday    Espresso        40.0
Friday        Friday    Espresso        45.0
Saturday    Saturday    Espresso        45.0
Sunday        Sunday    Espresso        45.0
NaN              NaN         NaN       100.0

In [105]:
for index, row in coffee.iterrows():
    print(index)
    print(row,["Units Sold"])
    print("\n\n")

Monday
Day              Monday
Coffee Type    Espresso
Units Sold         25.0
Name: Monday, dtype: object ['Units Sold']



Monday
Day            Monday
Coffee Type     Latte
Units Sold       15.0
Name: Monday, dtype: object ['Units Sold']



Tuesday
Day             Tuesday
Coffee Type    Espresso
Units Sold         30.0
Name: Tuesday, dtype: object ['Units Sold']



Tuesday
Day            Tuesday
Coffee Type      Latte
Units Sold        20.0
Name: Tuesday, dtype: object ['Units Sold']



Wednesday
Day            Wednesday
Coffee Type     Espresso
Units Sold          35.0
Name: Wednesday, dtype: object ['Units Sold']



Wednesday
Day            Wednesday
Coffee Type        Latte
Units Sold          25.0
Name: Wednesday, dtype: object ['Units Sold']



Thursday
Day            Thursday
Coffee Type    Espresso
Units Sold         40.0
Name: Thursday, dtype: object ['Units Sold']



Thursday
Day            Thursday
Coffee Type       Latte
Units Sold         30.0
Name: Thursday, dtype: object ['Units Sold']



Friday
Day              Friday
Coffee Type    Espresso
Units Sold         45.0
Name: Friday, dtype: object ['Units Sold']



Friday
Day            Friday
Coffee Type     Latte
Units Sold       35.0
Name: Friday, dtype: object ['Units Sold']



Saturday
Day            Saturday
Coffee Type    Espresso
Units Sold         45.0
Name: Saturday, dtype: object ['Units Sold']



Saturday
Day            Saturday
Coffee Type       Latte
Units Sold         35.0
Name: Saturday, dtype: object ['Units Sold']



Sunday
Day              Sunday
Coffee Type    Espresso
Units Sold         45.0
Name: Sunday, dtype: object ['Units Sold']



Sunday
Day            Sunday
Coffee Type     Latte
Units Sold       35.0
Name: Sunday, dtype: object ['Units Sold']



nan
Day              NaN
Coffee Type      NaN
Units Sold     100.0
Name: nan, dtype: object ['Units Sold']

In [106]:
biox.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [107]:
bios = biox

In [108]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [110]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [111]:
x=pd.Series([1,2,3,4,5])

In [112]:
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# filtering data set

RangeIndex(start=0, stop=5, step=1)

In [115]:
bios.loc[bios["height_cm"]>215]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [119]:
######### Short Hand Syntax

bios[(bios['height_cm'] >215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [122]:
bios[bios["name"].str.contains("ken")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5342,5361,Mukendi Mbuyi,1960-04-26,Kananga,Kasaï central,COD,Democratic Republic of the Congo,190.0,76.0,NaN
5350,5369,Carol Menken-Schaudt,1957-11-23,Albany,Oregon,USA,United States,195.0,77.0,NaN
5383,5402,Lukengu Ngalula,1971-08-11,Kinshasa,Kinshasa,COD,Democratic Republic of the Congo,183.0,64.0,NaN
5415,5434,Kakengwa Pikinini,1971-06-29,Bukavu,Sud-Kivu,COD,Democratic Republic of the Congo,178.0,79.0,NaN
5642,5665,Ole Bakken,1922-05-24,Harstad,Troms og Finnmark,NOR,Canada,195.0,95.0,1992-01-30
...,...,...,...,...,...,...,...,...,...,...
144661,148357,Leonie Gerken Schofield,1998-02-15,Chelmsford,England,GBR,Great Britain,NaN,NaN,NaN
144662,148358,Makayla Gerken Schofield,1999-06-04,Chelmsford,England,GBR,Great Britain,NaN,NaN,NaN
144741,148442,Leon Vockensperger,1999-08-25,Rosenheim,Bayern,GER,Germany,NaN,NaN,NaN
144980,148689,Fabian Wilkens Solheim,1996-04-10,Oslo,Oslo,NOR,Norway,175.0,NaN,NaN
144982,148691,Emilie Kalkenberg,1997-07-06,NaN,NaN,NaN,Norway,165.0,NaN,NaN

In [123]:
# mcKinney a data scientist and sd created pandas in 2008 
#  Reason for creation is while working at aqr capital management , was faced challenges analyzing large financial datset , existing tools like excel were inefficient for large scale data cleaning and analysis

In [124]:
# pandas is a powerful and pouplor library for data manupulation and analysisi


# work with csv and excel 
# Handles missing values easily
# built on numpy for fast computations

# why use pandas??

# performance
#easee of use 
#integration

In [ ]:
######### real example 

# dunance 
#retail #
# health care

In [ ]:
########import pandas


# import data as df

#df.head

# dataframe we will import into a variable and access that variable and work on it


# progress is so good

In [125]:
# pandas head and tail

In [ ]:
# df.head(10)
# df.tail(15)

# column 'rows' , what type of data